# Generated by Django 4.1.7 on 2023-03-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Spammers",
            fields=[
                (
                    "telegram_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="TelegramID"
                    ),
                ),
                (
                    "from_cas",
                    models.BooleanField(default=False, verbose_name="From CAS"),
                ),
            ],
            options={
                "verbose_name": "Telegram ID",
                "verbose_name_plural": "Telegram IDs",
            },
        ),
    ]
