# Generated by Django 4.1.7 on 2023-03-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatAdmins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField(verbose_name="Telegram chat ID")),
                ("user_id", models.BigIntegerField(verbose_name="Telegram user ID")),
                (
                    "shadow_admin",
                    models.BooleanField(default=False, verbose_name="Shadow admin"),
                ),
                (
                    "can_delete",
                    models.BooleanField(
                        default=False, verbose_name="Can delete messages"
                    ),
                ),
                (
                    "can_ban",
                    models.BooleanField(default=False, verbose_name="Can ban users"),
                ),
            ],
            options={
                "verbose_name": "Chat Admin",
                "verbose_name_plural": "Chat Admins",
            },
        ),
        migrations.AddIndex(
            model_name="chatadmins",
            index=models.Index(
                fields=["chat_id", "user_id"], name="bot_chatadm_chat_id_0c7fdc_idx"
            ),
        ),
    ]
