# Generated by Django 4.1.7 on 2023-04-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_chatadmins_chatadmins_bot_chatadm_chat_id_0c7fdc_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWarn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                ("user_id", models.BigIntegerField(verbose_name="User ID")),
                ("chat_id", models.BigIntegerField(verbose_name="Chat ID")),
                ("comment", models.TextField(null=True, verbose_name="Comment")),
                (
                    "warn_type",
                    models.IntegerField(
                        choices=[
                            (1, "Warn"),
                            (2, "Unwarn"),
                            (3, "Ban"),
                            (4, "Unban"),
                            (5, "Mute"),
                            (6, "Unmute"),
                            (7, "Kick"),
                            (8, "SPAM"),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "User Warning",
                "verbose_name_plural": "User Warnings",
            },
        ),
        migrations.AddIndex(
            model_name="userwarn",
            index=models.Index(
                fields=["chat_id", "user_id", "-created", "warn_type"],
                name="bot_userwar_chat_id_539915_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userwarn",
            index=models.Index(
                fields=["created"], name="bot_userwar_created_3fadcb_idx"
            ),
        ),
    ]
